<?php if ($block['block_effect']) {
    $this->css($this->assetModule('css/block.css', 'blog'));
} ?>
<div class="blog-block">
    <?php if (!empty($block['resources'])) { ?>
        <div class="recent-post-list clearfix">
            <?php foreach ($block['resources'] as $post) { ?>
                <div class="recent-post-single clearfix h-post" itemprop="liveBlogUpdate" itemscope itemtype="http://schema.org/BlogPosting">
                    <div class="row">
                        <?php if ($post['main_image'] && $block['view_image']) { ?>
                            <div class="col-md-4">
                                <a itemprop="url" title="<?php echo $this->escape($post['title']); ?>"
                                   href="<?php echo $this->escape($post['postUrl']); ?>">
                                    <img itemprop="image" class="img-responsive img-rounded u-photo"
                                         src="<?php echo $this->escape($post['thumbUrl']); ?>"
                                         alt="<?php echo $this->escape($post['title']); ?>"/>
                                </a>
                            </div>
                        <?php } ?>
                        <div class="<?php if ($post['main_image'] && $block['view_image']) { ?>col-md-8<?php } else { ?>col-md-12<?php } ?>">
                            <div class="recent-post-single-title p-name" itemprop="name">
                                <h3 class="clearfix" itemprop="headline">
                                    <a itemprop="url" title="<?php echo $this->escape($post['title']); ?>"
                                       href="<?php echo $this->escape($post['postUrl']); ?>">
                                        <?php echo $this->escape($post['title']); ?>
                                    </a>
                                </h3>
                            </div>
                            <?php if ($block['view_time'] || $block['view_hits']) { ?>
                            <div class="recent-post-single-information small">
                                <ul class="clearfix list-inline recent-post-time">
                                    <?php if ($block['view_time']) { ?>
                                        <li class="list-inline-item">
                                            <i class="fa fa-clock-o"></i> <?php echo $this->escape($post['time_create_view']); ?>
                                        </li>
                                    <?php } ?>
                                    <?php if ($block['view_hits']) { ?>
                                        <li class="list-inline-item">
                                            <i class="fa fa-eye"></i> <?php echo $this->escape(_number($post['hits'])); ?>
                                        </li>
                                    <?php } ?>
                                </ul>
                            </div>
                            <?php } ?>
                            <?php if (!empty($post['text_summary']) && $block['view_summary']) { ?>
                                <div class="recent-post-single-summery clearfix p-summary" itemprop="articleBody description">
                                    <?php echo $post['text_summary']; ?>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
        <?php if ($block['view_more_link']) { ?>
            <div class="recent-event-more clearfix">
                <a title="<?php echo _b('More posts'); ?>"
                   href="<?php echo $this->escape($block['morelink']); ?>"><?php echo _b('More posts'); ?></a>
            </div>
        <?php } ?>
    <?php } ?>
</div>